# Utilisation de l'image de base officielle PostgreSQL
FROM postgres:latest

# Port sur lequel PostgreSQL écoutera (par défaut : 5432)
EXPOSE 5432

# Commande pour démarrer PostgreSQL
CMD ["postgres"]
